export const sampleProperties: PropertyListing[] = [
  {
    id: "pune-001",
    title: "Luxury 3 BHK Apartment, Koregaon Park",
    description:
      "North-facing premium apartment with panoramic city views, marble flooring, and modular kitchen.",
    price: 28500000,
    currency: "INR",
    type: "Apartment",
    bhk: 3,
    baths: 2,
    area: 1850,
    location: { lat: 18.5362, lng: 73.8939 },
    address: {
      locality: "Koregaon Park",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
      "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Verified Agent",
      furnishedStatus: "Semi Furnished",
      amenities: [
        "Swimming Pool",
        "Gym",
        "24/7 Security",
        "Club House",
        "Power Backup",
      ],
    },
  },
  {
    id: "pune-002",
    title: "Modern 2 BHK, Hinjewadi IT Park",
    description:
      "Perfect for professionals, minutes from tech parks with smart home features.",
    price: 11500000,
    currency: "INR",
    type: "Apartment",
    bhk: 2,
    baths: 3,
    area: 1050,
    location: { lat: 18.5913, lng: 73.7389 },
    address: {
      locality: "Hinjewadi Phase 1",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
      "https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Owner",
      furnishedStatus: "Fully Furnished",
      amenities: [
        "High-Speed Internet",
        "Power Backup",
        "Gym",
        "Shopping Complex",
      ],
    },
  },
  {
    id: "pune-003",
    title: "Spacious 4 BHK Villa, Baner",
    description:
      "Majestic independent villa with private garden in a gated community.",
    price: 85000000,
    currency: "INR",
    type: "Villa",
    bhk: 4,
    baths: 4,
    area: 6000,
    location: { lat: 18.559, lng: 73.7868 },
    address: {
      locality: "Baner",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Builder",
      furnishedStatus: "Unfurnished",
      amenities: [
        "Private Garden",
        "Car Parking (4)",
        "Gated Community",
        "Home Automation",
      ],
    },
  },
  {
    id: "pune-004",
    title: "Penthouse with Terrace, Viman Nagar",
    description:
      "Exclusive penthouse with massive private terrace and panoramic city views.",
    price: 65000000,
    currency: "INR",
    type: "Penthouse",
    bhk: 3,
    baths: 3,
    area: 3125,
    location: { lat: 18.5679, lng: 73.9143 },
    address: {
      locality: "Viman Nagar",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/7031406/pexels-photo-7031406.jpeg",
      "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg",
      "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Verified Agent",
      furnishedStatus: "Fully Furnished",
      amenities: [
        "Private Terrace",
        "Jacuzzi",
        "Home Theatre",
        "Concierge Service",
      ],
    },
  },
  {
    id: "pune-005",
    title: "3 BHK Resale Apartment, Kothrud",
    description:
      "Well-maintained apartment in peaceful, established neighborhood near schools and markets.",
    price: 18500000,
    currency: "INR",
    type: "Apartment",
    bhk: 3,
    baths: 2,
    area: 2000,
    location: { lat: 18.5074, lng: 73.8077 },
    address: {
      locality: "Kothrud",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg",
      "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg",
      "https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Owner",
      furnishedStatus: "Semi Furnished",
      amenities: [
        "Parking (2)",
        "24/7 Water Supply",
        "Children's Park",
        "Security",
      ],
    },
  },
  {
    id: "pune-006",
    title: "Affordable 2 BHK, Wakad",
    description:
      "Budget-friendly apartment with excellent connectivity to Hinjewadi and Baner.",
    price: 9800000,
    currency: "INR",
    type: "Apartment",
    bhk: 2,
    baths: 2,
    area: 980,
    location: { lat: 18.5986, lng: 73.7645 },
    address: {
      locality: "Wakad",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
      "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg",
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
    ],
    details: {
      possessionStatus: "Under Construction",
      listedBy: "Builder",
      furnishedStatus: "Unfurnished",
      amenities: ["Lift", "Power Backup", "Parking"],
    },
  },
  {
    id: "pune-007",
    title: "Luxury 4 BHK Sky Villa, Aundh",
    description:
      "High-rise sky villa with premium interiors and city skyline views.",
    price: 72000000,
    currency: "INR",
    type: "Villa",
    bhk: 4,
    baths: 4,
    area: 4200,
    location: { lat: 18.561, lng: 73.807 },
    address: {
      locality: "Aundh",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg",
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg",
      "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Verified Agent",
      furnishedStatus: "Fully Furnished",
      amenities: ["Infinity Pool", "Gym", "Valet Parking"],
    },
  },
  {
    id: "pune-008",
    title: "1 BHK Compact Home, Hadapsar",
    description: "Ideal starter home close to Magarpatta City and IT offices.",
    price: 6200000,
    currency: "INR",
    type: "Apartment",
    bhk: 1,
    baths: 1,
    area: 550,
    location: { lat: 18.5089, lng: 73.926 },
    address: {
      locality: "Hadapsar",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg",
      "https://images.pexels.com/photos/271795/pexels-photo-271795.jpeg",
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Owner",
      furnishedStatus: "Semi Furnished",
      amenities: ["Lift", "Security", "Power Backup"],
    },
  },
  {
    id: "pune-009",
    title: "Premium 3 BHK, Magarpatta City",
    description:
      "Apartment inside integrated township with top-class amenities.",
    price: 24500000,
    currency: "INR",
    type: "Apartment",
    bhk: 3,
    baths: 3,
    area: 1750,
    location: { lat: 18.5164, lng: 73.934 },
    address: {
      locality: "Magarpatta City",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg",
      "https://images.pexels.com/photos/276671/pexels-photo-276671.jpeg",
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Builder",
      furnishedStatus: "Semi Furnished",
      amenities: ["Township Living", "Swimming Pool", "Jogging Track"],
    },
  },
  {
    id: "pune-010",
    title: "Independent Bungalow, Pashan",
    description: "Peaceful bungalow near hills with private lawn and parking.",
    price: 92000000,
    currency: "INR",
    type: "Villa",
    bhk: 5,
    baths: 5,
    area: 7000,
    location: { lat: 18.5373, lng: 73.7921 },
    address: {
      locality: "Pashan",
      city: "Pune",
      state: "Maharashtra",
    },
    images: [
      "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg",
      "https://images.pexels.com/photos/164558/pexels-photo-164558.jpeg",
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg",
    ],
    details: {
      possessionStatus: "Ready to Move",
      listedBy: "Owner",
      furnishedStatus: "Fully Furnished",
      amenities: ["Private Lawn", "CCTV", "Servant Room"],
    },
  },
];
